table dim_service_category
	lineageTag: 434d837d-a85b-4d2b-9605-69343fd34f14

	column service_category_id
		dataType: int64
		formatString: 0
		lineageTag: b7ff5754-9105-4d6b-9ffa-69ab4c1dbfbe
		summarizeBy: none
		sourceColumn: service_category_id

		annotation SummarizationSetBy = Automatic

	column issue_category
		dataType: string
		lineageTag: 77759932-c37e-4e8b-8703-91c0527bbf26
		summarizeBy: none
		sourceColumn: issue_category

		annotation SummarizationSetBy = Automatic

	column root_cause_group
		dataType: string
		lineageTag: e80cb1b6-d2c9-4ec7-ab85-e558925cd6ad
		summarizeBy: none
		sourceColumn: root_cause_group

		annotation SummarizationSetBy = Automatic

	column severity_level
		dataType: string
		lineageTag: f200b137-7c9a-4e3a-804a-8c3152c0d17d
		summarizeBy: none
		sourceColumn: severity_level

		annotation SummarizationSetBy = Automatic

	column is_warranty_eligible_default
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2397393b-c6bf-4457-8b87-8fc9945d75a1
		summarizeBy: none
		sourceColumn: is_warranty_eligible_default

		annotation SummarizationSetBy = Automatic

	partition dim_service_category = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\AlexOchokiMogengo\Projects\SC\data\dim_service_category.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"service_category_id", Int64.Type}, {"issue_category", type text}, {"root_cause_group", type text}, {"severity_level", type text}, {"is_warranty_eligible_default", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

