table dim_asset
	lineageTag: 9193b0c7-1ed9-40c3-bede-072fdcb3b64c

	measure 'Active PAYG Assets' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_installations[installation_id]),
			    fact_installations[install_status] = "Installed"
			)
		formatString: 0
		lineageTag: 2120ec81-8f88-452e-85e3-fb57f65acddf

	measure 'Total Paid' =
			
			SUM(fact_payments[paid_amount_kes])
		formatString: #,0
		lineageTag: afe9d5a1-b42d-44f0-bb16-6eb63c821a5d

	measure 'Paid Amount (KES)' =
			
			CALCULATE(
			    SUM(fact_payments[paid_amount_kes]),
			    fact_payments[is_reversal_flag] <> TRUE()
			)
		formatString: #,0
		lineageTag: 08646c8b-836b-4594-98f3-1070d9b8446a

	measure 'Expected Amount (KES)' =
			
			SUM(fact_payments[expected_amount_kes])
		formatString: #,0
		lineageTag: 7f4a601e-ec3b-46dc-b040-9d448676fa08

	measure 'Cash Collected (KES)' =
			
			[Paid Amount (KES)]
		formatString: 0
		lineageTag: e1a94542-2f0c-4afe-967a-5ec6ada11a95

	measure 'Portfolio Outstanding Principal (KES)' =
			
			SUM(fact_loan_snapshot_monthly[outstanding_principal_kes])
		formatString: #,0
		lineageTag: b64c5fe1-0357-4049-acc2-422a07ed7193

	measure 'Arrears Amount (KES)' =
			
			SUM(fact_loan_snapshot_monthly[arrears_amount_kes])
		formatString: #,0
		lineageTag: d9ddcd73-a02e-462d-96b4-21024d350521

	measure 'New Installs' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_installations[installation_id]),
			    NOT ISBLANK(fact_installations[actual_install_date_key])
			)
		formatString: #,0
		lineageTag: 2c1513aa-f806-4a76-a820-c522e5c07ec6

	measure 'New Installs WTD' =
			
			CALCULATE(
			    [New Installs],
			    DATESWTD(dim_date[date])
			)
		lineageTag: b2a3286d-2530-43bc-8e3d-861261439431

	measure 'New Installs MTD' =
			
			CALCULATE(
			    [New Installs],
			    DATESMTD(dim_date[date])
			)
		formatString: #,0
		lineageTag: 70f57ac1-826e-48c2-b693-cb4da400118f

	measure 'Repayment Rate %' =
			
			DIVIDE([Paid Amount (KES)], [Expected Amount (KES)])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 65eccc8c-3b76-4a2a-9fb8-10be658793ab

	measure 'PAR30 Principal (KES)' =
			
			CALCULATE(
			    [Portfolio Outstanding Principal (KES)],
			    fact_loan_snapshot_monthly[dpd] >= 30
			)
		formatString: #,0
		lineageTag: a246d4c8-e545-4d15-959c-c50fc81f864d

	measure 'PAR30 %' =
			
			DIVIDE([PAR30 Principal (KES)], [Portfolio Outstanding Principal (KES)])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f3ac11f5-1873-4112-bebd-e31165a56b75

	measure 'PAR90 Principal (KES)' =
			
			CALCULATE(
			    [Portfolio Outstanding Principal (KES)],
			    fact_loan_snapshot_monthly[dpd] >= 90
			)
		formatString: #,0
		lineageTag: 325ee7e5-299d-40bd-bf28-5ac2dc75d654

	measure 'PAR90 %' =
			
			DIVIDE([PAR90 Principal (KES)], [Portfolio Outstanding Principal (KES)])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d03d3f3c-36be-4fd8-8cad-122ba2a8fd24

	measure 'Install Backlog' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_installations[installation_id]),
			    ISBLANK(fact_installations[actual_install_date_key])
			)
		formatString: #,0
		lineageTag: 84e18769-fc46-4c0e-8b97-39c0437eb0b5

	measure 'Tickets Closed' =
			
			CALCULATE(
			    COUNTROWS(fact_service_tickets),
			    NOT ISBLANK(fact_service_tickets[ticket_close_date_key])
			)
		formatString: #,0
		lineageTag: 6c30ff03-5d5c-495d-89c2-2b4df34aca99

	measure 'Tickets Closed Met SLA' =
			
			CALCULATE(
			    [Tickets Closed],
			    fact_service_tickets[sla_met_flag] = TRUE()
			)
		formatString: #,0
		lineageTag: b0667c8d-2aeb-44b1-b3e6-3450d6254b39

	measure 'Service SLA %' =
			
			DIVIDE([Tickets Closed Met SLA], [Tickets Closed])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 62270c97-93d9-4203-99e2-4dbd03bb16c5

	measure 'Install Backlog MoM %' =
			
			VAR Curr = CALCULATE([Install Backlog], DATESMTD(dim_date[date]))
			VAR Prev = CALCULATE([Install Backlog], PREVIOUSMONTH(dim_date[date]))
			RETURN DIVIDE(Curr - Prev, Prev)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0027a81c-cf0f-46a3-a05b-b564605f5d33

	column asset_sk
		dataType: int64
		formatString: 0
		lineageTag: f28c1427-d2ed-47cb-ab3a-8ab3bc8b9dc9
		summarizeBy: none
		sourceColumn: asset_sk

		annotation SummarizationSetBy = Automatic

	column asset_id
		dataType: string
		lineageTag: 7e14c70f-159f-490a-9815-b57b8ae87835
		summarizeBy: none
		sourceColumn: asset_id

		annotation SummarizationSetBy = Automatic

	column product_sk
		dataType: int64
		formatString: 0
		lineageTag: 44272e39-9572-481b-bcfd-a745ae07d04b
		summarizeBy: none
		sourceColumn: product_sk

		annotation SummarizationSetBy = Automatic

	column serial_no
		dataType: string
		lineageTag: 4f1b3c42-e851-4a4e-b609-e44d2d36f1da
		summarizeBy: none
		sourceColumn: serial_no

		annotation SummarizationSetBy = Automatic

	column manufacture_batch
		dataType: string
		lineageTag: aeb0a0c6-b99c-43b1-9dcc-c2c3b0c80a1f
		summarizeBy: none
		sourceColumn: manufacture_batch

		annotation SummarizationSetBy = Automatic

	column warranty_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7a6561ff-a94a-43ce-824d-0a029bf6d5ea
		summarizeBy: none
		sourceColumn: warranty_start_date

		variation Variation
			isDefault
			relationship: b6c90047-4fc4-407f-a3f2-40749984e330
			defaultHierarchy: LocalDateTable_fb9ad7be-1ba1-41d9-9874-bf5da614ad86.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column warranty_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 73ddeb7a-b079-42ad-8dc3-9d2b9619f90d
		summarizeBy: none
		sourceColumn: warranty_end_date

		variation Variation
			isDefault
			relationship: 2ca921d5-b7c2-48d2-9122-663d0f18446e
			defaultHierarchy: LocalDateTable_f7356953-636d-4938-a070-f5fe0938f934.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column status
		dataType: string
		lineageTag: 386c3e7c-d4ad-4281-b607-811570fb0f89
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition dim_asset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\AlexOchokiMogengo\Projects\SC\data\dim_asset.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"asset_sk", Int64.Type}, {"asset_id", type text}, {"product_sk", Int64.Type}, {"serial_no", type text}, {"manufacture_batch", type text}, {"warranty_start_date", type date}, {"warranty_end_date", type date}, {"status", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

