table dim_financing_plan
	lineageTag: 17d62013-3694-4581-8f64-035e91b8052a

	column plan_id
		dataType: int64
		formatString: 0
		lineageTag: f8fc8162-3b0a-4d98-98bb-3b12e199c2ac
		summarizeBy: none
		sourceColumn: plan_id

		annotation SummarizationSetBy = Automatic

	column plan_name
		dataType: string
		lineageTag: 9a7bf819-1279-4434-b695-d206cdb1702b
		summarizeBy: none
		sourceColumn: plan_name

		annotation SummarizationSetBy = Automatic

	column tenor_months
		dataType: int64
		formatString: 0
		lineageTag: c439520b-cece-4806-b15d-944938b89f55
		summarizeBy: sum
		sourceColumn: tenor_months

		annotation SummarizationSetBy = Automatic

	column deposit_pct
		dataType: int64
		formatString: 0
		lineageTag: 6c6d92af-7530-4cd8-8a17-ca5bfda95f2c
		summarizeBy: sum
		sourceColumn: deposit_pct

		annotation SummarizationSetBy = Automatic

	column interest_rate_annual_pct
		dataType: int64
		formatString: 0
		lineageTag: d79a6005-d624-475c-9b48-679b052d1030
		summarizeBy: sum
		sourceColumn: interest_rate_annual_pct

		annotation SummarizationSetBy = Automatic

	column payment_frequency
		dataType: string
		lineageTag: 1c76745f-99fd-4a5b-ad31-04852bab3fe7
		summarizeBy: none
		sourceColumn: payment_frequency

		annotation SummarizationSetBy = Automatic

	column grace_period_days
		dataType: int64
		formatString: 0
		lineageTag: db472360-0ba0-4d97-ad88-8465d867c4ce
		summarizeBy: sum
		sourceColumn: grace_period_days

		annotation SummarizationSetBy = Automatic

	partition dim_financing_plan = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\AlexOchokiMogengo\Projects\SC\data\dim_financing_plan.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"plan_id", Int64.Type}, {"plan_name", type text}, {"tenor_months", Int64.Type}, {"deposit_pct", Int64.Type}, {"interest_rate_annual_pct", Int64.Type}, {"payment_frequency", type text}, {"grace_period_days", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

