table fact_asset_usage_daily
	lineageTag: 6d492562-b950-4706-bd0f-aba1f5133561

	column usage_date_key
		dataType: int64
		formatString: 0
		lineageTag: 24211c13-d172-4392-8fdd-b9e2e08f1b1c
		summarizeBy: none
		sourceColumn: usage_date_key

		annotation SummarizationSetBy = Automatic

	column asset_sk
		dataType: int64
		formatString: 0
		lineageTag: bb3997e4-8e0b-4ac5-a25a-3bfb51695919
		summarizeBy: none
		sourceColumn: asset_sk

		annotation SummarizationSetBy = Automatic

	column customer_sk
		dataType: int64
		formatString: 0
		lineageTag: 173d913f-19cc-4bd1-a82d-86a3ba5126ee
		summarizeBy: none
		sourceColumn: customer_sk

		annotation SummarizationSetBy = Automatic

	column geo_id
		dataType: int64
		formatString: 0
		lineageTag: d3372583-d65d-4e2a-a9ac-390bd8a82f9c
		summarizeBy: sum
		sourceColumn: geo_id

		annotation SummarizationSetBy = Automatic

	column product_sk
		dataType: int64
		formatString: 0
		lineageTag: 3885ea66-c7e6-45f0-8715-44733f8cffea
		summarizeBy: sum
		sourceColumn: product_sk

		annotation SummarizationSetBy = Automatic

	column pump_runtime_hours
		dataType: double
		lineageTag: 4cff9939-775a-4e64-8dcc-6c82433f962f
		summarizeBy: sum
		sourceColumn: pump_runtime_hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estimated_water_volume_liters
		dataType: int64
		formatString: 0
		lineageTag: 3801c72a-d772-4544-8eea-f59d2cf6d315
		summarizeBy: sum
		sourceColumn: estimated_water_volume_liters

		annotation SummarizationSetBy = Automatic

	column fault_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8039497b-410b-4de7-b6f4-4fba2061221d
		summarizeBy: none
		sourceColumn: fault_flag

		annotation SummarizationSetBy = Automatic

	column low_usage_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7a80260e-2f84-4768-9e58-6dfa7310035c
		summarizeBy: none
		sourceColumn: low_usage_flag

		annotation SummarizationSetBy = Automatic

	partition fact_asset_usage_daily = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\AlexOchokiMogengo\Projects\SC\data\fact_asset_usage_daily.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"usage_date_key", Int64.Type}, {"asset_sk", Int64.Type}, {"customer_sk", Int64.Type}, {"geo_id", Int64.Type}, {"product_sk", Int64.Type}, {"pump_runtime_hours", type number}, {"estimated_water_volume_liters", Int64.Type}, {"fault_flag", type logical}, {"low_usage_flag", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

