table fact_installations
	lineageTag: 90f8b71f-c323-405c-ae0a-2921b364e5fb

	column installation_id
		dataType: string
		lineageTag: 3ce0e967-abed-47eb-a81d-1c90674c5f35
		summarizeBy: none
		sourceColumn: installation_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: d9c659ed-f19d-4646-91aa-b9a2e57fa414
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column scheduled_install_date_key
		dataType: int64
		formatString: 0
		lineageTag: fcc9d3d3-0ad9-4504-a4e6-f2917417376b
		summarizeBy: sum
		sourceColumn: scheduled_install_date_key

		annotation SummarizationSetBy = Automatic

	column actual_install_date_key
		dataType: int64
		formatString: 0
		lineageTag: d78b3e81-9d08-466e-8cc9-d5c5bea21a0a
		summarizeBy: sum
		sourceColumn: actual_install_date_key

		annotation SummarizationSetBy = Automatic

	column customer_sk
		dataType: int64
		formatString: 0
		lineageTag: 54a426df-808f-4948-96d6-d9e114260023
		summarizeBy: none
		sourceColumn: customer_sk

		annotation SummarizationSetBy = Automatic

	column product_sk
		dataType: int64
		formatString: 0
		lineageTag: deda367f-ec31-48b0-a048-08dd49f5a422
		summarizeBy: none
		sourceColumn: product_sk

		annotation SummarizationSetBy = Automatic

	column installer_team_sk
		dataType: int64
		formatString: 0
		lineageTag: 4d40c885-7d39-4adb-a1bb-97fdfd607056
		summarizeBy: sum
		sourceColumn: installer_team_sk

		annotation SummarizationSetBy = Automatic

	column geo_id
		dataType: int64
		formatString: 0
		lineageTag: 9b787832-39fe-422c-88b3-52b5f22dabe9
		summarizeBy: sum
		sourceColumn: geo_id

		annotation SummarizationSetBy = Automatic

	column install_status
		dataType: string
		lineageTag: 77915be7-06e2-45fe-bc44-f1b2ea963e61
		summarizeBy: none
		sourceColumn: install_status

		annotation SummarizationSetBy = Automatic

	column install_delay_days
		dataType: int64
		formatString: 0
		lineageTag: d28a5a04-69b7-402e-8186-57f9499a5849
		summarizeBy: sum
		sourceColumn: install_delay_days

		annotation SummarizationSetBy = Automatic

	column training_provided_flag
		dataType: int64
		formatString: 0
		lineageTag: 3813cf23-9ed6-4322-933f-672b154b02c9
		summarizeBy: sum
		sourceColumn: training_provided_flag

		annotation SummarizationSetBy = Automatic

	column installation_quality_score
		dataType: int64
		formatString: 0
		lineageTag: 570a97b7-1747-42b6-96b5-b679eafd8c19
		summarizeBy: sum
		sourceColumn: installation_quality_score

		annotation SummarizationSetBy = Automatic

	column activation_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6cc7d446-7c37-4650-9add-1e63f14448ac
		summarizeBy: none
		sourceColumn: activation_flag

		annotation SummarizationSetBy = Automatic

	partition fact_installations = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\AlexOchokiMogengo\Projects\SC\data\fact_installations.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"installation_id", type text}, {"order_id", type text}, {"scheduled_install_date_key", Int64.Type}, {"actual_install_date_key", Int64.Type}, {"customer_sk", Int64.Type}, {"product_sk", Int64.Type}, {"installer_team_sk", Int64.Type}, {"geo_id", Int64.Type}, {"install_status", type text}, {"install_delay_days", Int64.Type}, {"training_provided_flag", Int64.Type}, {"installation_quality_score", Int64.Type}, {"activation_flag", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

